# ce fichier permet de récupérer les secrets depuis vault 
apiVersion: external-secrets.io/v1 # j'ai enlevé v1beta1 car il n'est plus supporté
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # url vault par defaut sur k8s
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "miage-bank-role"
          # on s'authentifie avec le service account
          serviceAccountRef:
            name: {{ include "miage-bank.fullname" . }}-sa 

---
# on indique a kubernetes quoi aller chercher dans vault pour fabriquer notre secret local
apiVersion: external-secrets.io/v1 # j'ai enlevé v1beta1 car il n'est plus supporté
kind: ExternalSecret
metadata:
  name: miage-bank-externalsecret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    # on indique a kubernetes de generer un secret local portant ce nom exact
    name: miage-bank-secrets 
    creationPolicy: Owner
  data:
    # on convertit les données de Vault vers des variables d'environnement lisibles par nos conteneurs
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: miage-bank/database
        property: mysql_db
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: miage-bank/database
        property: mysql_password
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: miage-bank/database
        property: mongo_user
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: miage-bank/database
        property: mongo_password
    - secretKey: MONGO_DATABASE
      remoteRef:
        key: miage-bank/database
        property: mongo_db
