{{- if .Values.vault.enabled }}

# 1. SecretStore : La configuration de la connexion à Vault
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: miage-bank-vault-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authPath | quote }}
          role: "miage-bank-role" # Le rôle configuré dans Vault lors de votre TP12/13
          serviceAccountRef:
            name: {{ .Values.global.serviceAccountName }} # Utilisation du RBAC défini précédemment

---

# 2. ExternalSecret : L'ordre d'aller chercher le secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miage-bank-db-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h" # ESO vérifiera toutes les heures si le mot de passe a changé dans Vault
  secretStoreRef:
    name: miage-bank-vault-store
    kind: SecretStore
  target:
    name: db-credentials # Le nom du Secret Kubernetes classique qui sera généré
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.secretPath }} # Récupère toutes les paires clé/valeur à ce chemin
{{- end }}
