apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: miage-bank-vault-store
  # Helm gérera automatiquement le namespace
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "miage-bank-role"
          serviceAccountRef:
            name: "miage-bank-sa"
