apiVersion: v1
kind: Secret
metadata:
  name: miage-bank-vault-store  # Gardez bien le nom attendu par votre application
  namespace: miage-bank
type: Opaque
data:
  NOM_DE_LA_CLE_1: "VFZrMDlreVVIYlpzS0pRRzZRTXdJY1B3RjF5WHgzeWc5SCs3eGNIQzBTdkw="
  NOM_DE_LA_CLE_2: "bTd3bWNpWnlHZEZEUmo2MDhDUFhTeVo5VHRHR0NhRCtpS09EMCtYQjhhY20="
  NOM_DE_LA_CLE_3: "bFZLZGV4UDVMSFRYeE1EbzB2d1dTMFo4R2FNZkpnQ3lEUFNMTkJaMEd1WkM="
